
-- ridge regression 
       * evitar overfitting
        
       y=ax+b
       
       a,b = min[sum (y-y_hat)² ] ---> OLS
                       erro
       a,b = min[sum (y-y_hat)² + lambda*a²+....] ---> Ridge Regression
                       erro
       lambda é estimado via cross validation dos dados, no fundo a gente quer saber qual o lambda que  minimiza a variancia quando variamos os datasets
       
       video explicativo: https://www.youtube.com/watch?v=Q81RR3yKn30
       
       
 -lasso
 
       y=ax+b
       
       a,b = min[sum (y-y_hat)² ] ---> OLS
                       erro
       a,b = min[sum (y-y_hat)² + lambda*|a|+....] ---> lasso 
                       erro
                       
      * é tão bom quanto o Ridge regression
      * a grande diferença é que o lasso pode retirar variaveis (feature selection)
      
      
 link - Geometric interpretation of penalized linear regression
 
 Livros - 
     * Noções de Probabilidade e Estatística marcos magalhães 
 https://www.edusp.com.br/livros/nocoes-de-probabilidade-e-estatistica/

    *Morettin & Bussab - Estatística Básica
 

Lasso

In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge, Lasso
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import model_selection
import matplotlib.pyplot as plt
from sklearn.linear_model import RidgeCV, LassoCV

In [4]:
#carregando os dados
df = pd.read_csv("../data/Hitters.csv")
df.head()

AtBat  Hits  HmRun  Runs  RBI  Walks  Years  CAtBat  CHits  CHmRun  CRuns  \
0    293    66      1    30   29     14      1     293     66       1     30   
1    315    81      7    24   38     39     14    3449    835      69    321   
2    479   130     18    66   72     76      3    1624    457      63    224   
3    496   141     20    65   78     37     11    5628   1575     225    828   
4    321    87     10    39   42     30      2     396    101      12     48   

   CRBI  CWalks League Division  PutOuts  Assists  Errors  Salary NewLeague  
0    29      14      A        E      446       33      20     NaN         A  
1   414     375      N        W      632       43      10   475.0         N  
2   266     263      A        W      880       82      14   480.0         A  
3   838     354      N        E      200       11       3   500.0         N  
4    46      33      N        E      805       40       4    91.5         N

In [5]:
#carregando os dados
df = pd.read_csv("../data/Hitters.csv")

#apagando dados nulos
df = df.dropna()

dms = pd.get_dummies(df[['League', 'Division', 'NewLeague']])

y = df["Salary"]

X_ = df.drop(['Salary', 'League', 'Division', 'NewLeague'], axis=1).astype('float64')

X = pd.concat([X_, dms[['League_N', 'Division_W', 'NewLeague_N']]], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.25, 
                                                    random_state=42)

In [6]:
df.head()

AtBat  Hits  HmRun  Runs  RBI  Walks  Years  CAtBat  CHits  CHmRun  CRuns  \
1    315    81      7    24   38     39     14    3449    835      69    321   
2    479   130     18    66   72     76      3    1624    457      63    224   
3    496   141     20    65   78     37     11    5628   1575     225    828   
4    321    87     10    39   42     30      2     396    101      12     48   
5    594   169      4    74   51     35     11    4408   1133      19    501   

   CRBI  CWalks League Division  PutOuts  Assists  Errors  Salary NewLeague  
1   414     375      N        W      632       43      10   475.0         N  
2   266     263      A        W      880       82      14   480.0         A  
3   838     354      N        E      200       11       3   500.0         N  
4    46      33      N        E      805       40       4    91.5         N  
5   336     194      A        W      282      421      25   750.0         A

In [7]:
lasso_model = Lasso().fit(X_train,y_train)

/home/gustavoalmeida/.local/share/virtualenvs/mba-icmc-data_science-introducao_data_scie-Xc884u1h/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.257e+06, tolerance: 3.899e+03
  model = cd_fast.enet_coordinate_descent(


In [8]:
lasso_model.intercept_

-5.587450677336506

In [9]:
#sobre as variaveis que temos descobrimos o coeficiente de lasso delas

lasso_model.coef_

array([-1.74875691e+00,  8.59204135e+00,  6.67993798e+00, -3.06715333e+00,
       -1.91843070e+00,  5.32372890e+00,  8.39184117e+00, -1.63172447e-01,
       -8.22311277e-02, -3.93602861e-01,  1.71118530e+00,  6.55730545e-01,
       -6.48379405e-01,  2.59815358e-01,  2.73041157e-01, -4.41440454e-01,
        8.54474011e+01, -9.59701213e+01, -2.13086605e+01])

In [10]:
# Aqui a gente testa os diferentes lambdas

lasso = Lasso()
coefs = []
alphas = np.random.randint(0,1000,100)


for a in alphas:
    lasso.set_params(alpha = a)
    lasso.fit(X_train,y_train)
    coefs.append(lasso.coef_)

/home/gustavoalmeida/.local/share/virtualenvs/mba-icmc-data_science-introducao_data_scie-Xc884u1h/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.028e+03, tolerance: 3.899e+03
  model = cd_fast.enet_coordinate_descent(
/home/gustavoalmeida/.local/share/virtualenvs/mba-icmc-data_science-introducao_data_scie-Xc884u1h/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.348e+03, tolerance: 3.899e+03
  model = cd_fast.enet_coordinate_descent(
/home/gustavoalmeida/.local/share/virtualenvs/mba-icmc-data_science-introducao_data_scie-Xc884u1h/lib/python3.8/site-packages/skle

In [11]:
lasso_model.predict(X_train)[:5]

array([377.26270596, 786.51524513, 495.14140718, 117.19492966,
       429.04228506])

In [12]:
lasso_model.predict(X_test)[:5]

array([ 609.18826367,  696.96810702, 1009.06157391,  412.22773375,
        409.25851712])

In [13]:
y_pred = lasso_model.predict(X_test)
np.sqrt(mean_squared_error(y_test,y_pred))
#RMSE

356.0975884554034

In [14]:
#quanto maior melhor 
r2_score(y_test, y_pred)

0.41422798132366156

In [15]:
lasso_cv_model = LassoCV(alphas = np.random.randint(0,1000,100), cv = 10, max_iter = 100000).fit(X_train,y_train)

In [16]:
lasso_cv_model.alpha_

186

In [17]:
lasso_tuned = Lasso().set_params(alpha = lasso_cv_model.alpha_).fit(X_train,y_train)

y_pred_tuned = lasso_tuned.predict(X_test)

np.sqrt(mean_squared_error(y_test,y_pred_tuned))
#RMSE

363.0497306597977

In [18]:
# We know that the coefficients not used in Lasso Regression are set to zero. So let's observe.

pd.Series(lasso_tuned.coef_, index = X_train.columns )

AtBat         -1.132148
Hits           5.545718
HmRun          0.000000
Runs           0.000000
RBI            0.000000
Walks          2.794677
Years          0.000000
CAtBat        -0.169961
CHits          0.228254
CHmRun        -0.000000
CRuns          1.063636
CRBI           0.472739
CWalks        -0.213008
PutOuts        0.272994
Assists        0.177384
Errors        -0.000000
League_N       0.000000
Division_W    -0.000000
NewLeague_N    0.000000
dtype: float64

In [19]:
#Ridge Regression

In [20]:
from sklearn.linear_model import Ridge, RidgeCV
from sklearn.metrics import mean_squared_error

# ajusta o modelo ridge regression
ridge2 = Ridge(alpha = 0, normalize = True)
ridge2.fit(X_train, y_train)             # Fit a ridge regression on the training data
y_pred = ridge2.predict(X_test)           # Use this model to predict the test data
RSME = mean_squared_error(y_test, y_pred)
print("RSME:", RSME)          # Calculate the test MSE

RSME: 127487.05257542146


/home/gustavoalmeida/.local/share/virtualenvs/mba-icmc-data_science-introducao_data_scie-Xc884u1h/lib/python3.8/site-packages/sklearn/linear_model/_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(


In [21]:
from sklearn.linear_model import Ridge, RidgeCV
from sklearn.metrics import mean_squared_error

# ajusta o modelo ridge regression
ridge2 = Ridge(alpha = 3, normalize = True)
ridge2.fit(X_train, y_train)             # Fit a ridge regression on the training data
y_pred = ridge2.predict(X_test)           # Use this model to predict the test data
RSME = mean_squared_error(y_test, y_pred)
print("RSME:", RSME)          # Calculate the test MSE

RSME: 153483.22038906734


/home/gustavoalmeida/.local/share/virtualenvs/mba-icmc-data_science-introducao_data_scie-Xc884u1h/lib/python3.8/site-packages/sklearn/linear_model/_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
